### PR TITLE
Remove references to default credentials

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
@derek-ho Can you update this line: https://github.com/opensearch-project/reporting-cli/blob/861b7ea6b6121ee3f019b8737df056ac95469d98/test/cli.js#L9 as well?

**Comment by derek-ho** [comment]
@Swiddis @sumukhswamy can you folks please help me with this? CI is failing since: https://github.com/opensearch-project/reporting-cli/pull/53. Turning this PR as draft since it should be merged after 2.12.0 release.

**Comment by DarshitChanpura** [comment]
Now that 2.12 is released this should be unblocked. Would one of the maintainers mind bringing it across the finish line?

**Review by joshuali925 — APPROVED** [review]

**Review by rupal-bq — APPROVED** [review]

**Comment by rupal-bq** [comment]
CI failure not related to this change

**Pull request merged**
